kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8swatchcrd
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - k8spodcnt.io
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8swatchcrd
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8swatchcrd
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8swatchcrd
subjects:
- kind: ServiceAccount
  name: k8swatchcrd
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: k8swatchcrd
  namespace: default
spec:
  serviceAccountName: k8swatchcrd
  containers:
  - name: k8swatchcrd
    image: herekar/k8swatchcrd:1.0
    imagePullPolicy: Always
    volumeMounts:
    - name: config-volume
      mountPath: /root
  restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: k8swatchcrd
