apiVersion: v1
kind: ConfigMap
metadata:
  name: k8swatchcrd
data:
  .k8swatchcrd.yaml: |
    resource:
      deployment: false
      replicationcontroller: false
      replicaset: false
      daemonset: false
      services: true
      pod: true
