kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8swatchcrd
rules:
- apiGroups: ["", "extensions", "k8spodcnt.io", "apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8swatchcrd-binding
subjects:
- kind: Group
  name: crdgroup
  apiGroup: ""
roleRef:
  kind: Role
  name: k8swatchcrd
  apiGroup: ""

