/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/k8swatchcrd/opt/pkg/apis/k8spodcnt/v1"
	scheme "github.com/k8swatchcrd/opt/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MonitorsGetter has a method to return a MonitorInterface.
// A group's client should implement this interface.
type MonitorsGetter interface {
	Monitors(namespace string) MonitorInterface
}

// MonitorInterface has methods to work with Monitor resources.
type MonitorInterface interface {
	Create(*v1.Monitor) (*v1.Monitor, error)
	Update(*v1.Monitor) (*v1.Monitor, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.Monitor, error)
	List(opts meta_v1.ListOptions) (*v1.MonitorList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Monitor, err error)
	MonitorExpansion
}

// monitors implements MonitorInterface
type monitors struct {
	client rest.Interface
	ns     string
}

// newMonitors returns a Monitors
func newMonitors(c *K8spodcntV1Client, namespace string) *monitors {
	return &monitors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the monitor, and returns the corresponding monitor object, and an error if there is any.
func (c *monitors) Get(name string, options meta_v1.GetOptions) (result *v1.Monitor, err error) {
	result = &v1.Monitor{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("monitors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Monitors that match those selectors.
func (c *monitors) List(opts meta_v1.ListOptions) (result *v1.MonitorList, err error) {
	result = &v1.MonitorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("monitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested monitors.
func (c *monitors) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("monitors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a monitor and creates it.  Returns the server's representation of the monitor, and an error, if there is any.
func (c *monitors) Create(monitor *v1.Monitor) (result *v1.Monitor, err error) {
	result = &v1.Monitor{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("monitors").
		Body(monitor).
		Do().
		Into(result)
	return
}

// Update takes the representation of a monitor and updates it. Returns the server's representation of the monitor, and an error, if there is any.
func (c *monitors) Update(monitor *v1.Monitor) (result *v1.Monitor, err error) {
	result = &v1.Monitor{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("monitors").
		Name(monitor.Name).
		Body(monitor).
		Do().
		Into(result)
	return
}

// Delete takes name of the monitor and deletes it. Returns an error if one occurs.
func (c *monitors) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("monitors").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *monitors) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("monitors").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched monitor.
func (c *monitors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Monitor, err error) {
	result = &v1.Monitor{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("monitors").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
