/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	k8spodcnt_v1 "github.com/k8swatchcrd/opt/pkg/apis/k8spodcnt/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMonitors implements MonitorInterface
type FakeMonitors struct {
	Fake *FakeK8spodcntV1
	ns   string
}

var monitorsResource = schema.GroupVersionResource{Group: "k8spodcnt", Version: "v1", Resource: "monitors"}

var monitorsKind = schema.GroupVersionKind{Group: "k8spodcnt", Version: "v1", Kind: "Monitor"}

// Get takes name of the monitor, and returns the corresponding monitor object, and an error if there is any.
func (c *FakeMonitors) Get(name string, options v1.GetOptions) (result *k8spodcnt_v1.Monitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(monitorsResource, c.ns, name), &k8spodcnt_v1.Monitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*k8spodcnt_v1.Monitor), err
}

// List takes label and field selectors, and returns the list of Monitors that match those selectors.
func (c *FakeMonitors) List(opts v1.ListOptions) (result *k8spodcnt_v1.MonitorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(monitorsResource, monitorsKind, c.ns, opts), &k8spodcnt_v1.MonitorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &k8spodcnt_v1.MonitorList{ListMeta: obj.(*k8spodcnt_v1.MonitorList).ListMeta}
	for _, item := range obj.(*k8spodcnt_v1.MonitorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested monitors.
func (c *FakeMonitors) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(monitorsResource, c.ns, opts))

}

// Create takes the representation of a monitor and creates it.  Returns the server's representation of the monitor, and an error, if there is any.
func (c *FakeMonitors) Create(monitor *k8spodcnt_v1.Monitor) (result *k8spodcnt_v1.Monitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(monitorsResource, c.ns, monitor), &k8spodcnt_v1.Monitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*k8spodcnt_v1.Monitor), err
}

// Update takes the representation of a monitor and updates it. Returns the server's representation of the monitor, and an error, if there is any.
func (c *FakeMonitors) Update(monitor *k8spodcnt_v1.Monitor) (result *k8spodcnt_v1.Monitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(monitorsResource, c.ns, monitor), &k8spodcnt_v1.Monitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*k8spodcnt_v1.Monitor), err
}

// Delete takes name of the monitor and deletes it. Returns an error if one occurs.
func (c *FakeMonitors) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(monitorsResource, c.ns, name), &k8spodcnt_v1.Monitor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMonitors) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(monitorsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &k8spodcnt_v1.MonitorList{})
	return err
}

// Patch applies the patch and returns the patched monitor.
func (c *FakeMonitors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *k8spodcnt_v1.Monitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(monitorsResource, c.ns, name, data, subresources...), &k8spodcnt_v1.Monitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*k8spodcnt_v1.Monitor), err
}
